/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef GAUSSEXPREV
#define GAUSSEXPREV

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ExpGaussRev : public RooAbsPdf {
public:
  ExpGaussRev() {} ; 
  ExpGaussRev(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2);
  ExpGaussRev(const ExpGaussRev& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ExpGaussRev(*this,newname); }
  // inline virtual ~ExpGaussRev() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ExpGaussRev,1) // Your description goes here...
};
 
#endif
