/*****************************************************************************
* Project: RooFit                                                           *
*                                                                           *
* This code was autogenerated by RooClassFactory                            *
*****************************************************************************/

#pragma once

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class FlattePDF : public RooAbsPdf {
public:
  FlattePDF() {}
  FlattePDF(const char *name, const char *title, RooAbsReal& _x, RooAbsReal& _mean, RooAbsReal& _gpi, RooAbsReal& _gk, RooAbsReal& _m0);
  FlattePDF(const FlattePDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FlattePDF(*this,newname); }
  inline virtual ~FlattePDF() { }

  /*
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  */

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy gpi ;
  RooRealProxy gk ;
  RooRealProxy m0 ;

  Double_t evaluate() const ;

private:

  ClassDef(FlattePDF,2)  // Flatte Function PDF for the |amplitude|^2 PDF
};
