/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef LANDAUEXPPDF
#define LANDAUEXPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class LandauExpPDF : public RooAbsPdf {
public:
  LandauExpPDF() {} ;
  LandauExpPDF(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
        RooAbsReal& _sigma,
        RooAbsReal& _e0,
	      RooAbsReal& _e1,
	      RooAbsReal& _e2,
        RooAbsReal& _er0,
        RooAbsReal& _er1);
  LandauExpPDF(const LandauExpPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new LandauExpPDF(*this,newname); }
  // inline virtual ~LandauExpPDF() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy e0 ;
  RooRealProxy e1 ;
  RooRealProxy e2 ;
  RooRealProxy er0 ;
  RooRealProxy er1 ;

  Double_t evaluate() const ;

private:

  ClassDef(LandauExpPDF,1) // Your description goes here...
};
 
#endif
