/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#pragma once

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RevCrystalBall : public RooAbsPdf {
public:
  RevCrystalBall() {} ;
  RevCrystalBall(const char *name, const char *title, RooAbsReal& _x, RooAbsReal& _p0, RooAbsReal& _p1, RooAbsReal& _p2, RooAbsReal& _p3);
  RevCrystalBall(const RevCrystalBall& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RevCrystalBall(*this,newname); }
  inline virtual ~RevCrystalBall() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;

  Double_t evaluate() const ;

private:

  ClassDef(RevCrystalBall,1) // Your description goes here...
};
